### ISSUE TITLE
Комментарии

### ISSUE THREAD

**Issue by FMRobot** [FrontenderMagazine/checkout-faster-with-Autofill#1]

**Comment by rabbiabram** [comment]
вот только что-то мне кажется, что авто-заполнение данных кредитки - не очень хорошо с точки зрения безопасности.Например, если вы реально отошли на 5 минут и кто-то решил помочь в строительстве "Звезду Смерти" на кистартере

**Comment by Semigradsky** [comment]
Идея для стартапа:
1. делаем поля ввода данных кредитки автозаполняемыми
2. убираем эти поля куда-нибудь за экран, чтобы их не было видно

``` css
.credit-fields {
position: absolute;
left: 1000000px;
}
```
1. ???
2. PROFIT!
